### ISSUE TITLE
Merging rules

### ISSUE THREAD

**Issue by kaitj** [khanlab/labelmerge#5]
From split labels, determine some set of rules to merge and override base label map. Will need to consider some sort of label harmonization.

### Ideas
* Use priority list for each labels, if conflict use higher priority (e.g. conflict = label in same voxel)
  * Have to consider "similar" labels from different maps may be named or labelled differently
* A base and an "override" label, where the override always takes priority over base

### Issues to consider
* Differing volumes for labels
  * Original workflow removed the existing label before adding in the new one (but both were also the same volume)
  * Could consider using the overlapping voxels

**Comment by jclauneuro** [comment]
Thanks, I would emphasize simplicity of merging rules. The situations where we have to formally deal with tiebreaker situations is limited. And as mentioned there is value in just "embracing the uncertainty" of having a voxel perhaps multiple labels (since data is inherently noisy/fuzzy).

**Comment by tkkuehn** [comment]
#20 Will add base/overlay merging rules. We can create separate issues for more complex rules as needed.
