### ISSUE TITLE
Deploy to PyPI

### ISSUE THREAD

**Issue by tkkuehn** [khanlab/labelmerge#50]
Labelmerge has only pure python dependencies so users could install it via `pip`, `pipx`, etc. For that reason I think we should at least consider deploying every release to PyPI (in addition to DockerHub). Snakebids has an action to do this that we could copy

**Comment by kaitj** [comment]
This is currently commented out, but will be included as part of #58. 

**Note to self: add PyPI API token**

**Comment by kaitj** [comment]
This is now possible as of `0.4.6`
