### ISSUE TITLE
Create Github actions

### ISSUE THREAD

**Issue by kaitj** [khanlab/labelmerge#6]
Create actions for the following:

- [x] Versioning
  - [x] Pre-release
  - [x] Release
- [x] Automatic assignment of reviewer and assignee

**Comment by kaitj** [comment]
Started to work on this. @tkkuehn do you want to generate a token (as `BP_BAP_TOKEN`) for this action or shall I? This would be for updating versioning on a protected branch (`main`).

I think as long as the token is from anyone with admin access, this should work.

**Comment by kaitj** [comment]
On the note of release, how should the release work (e.g. docker container, python package, etc.)? I think we should add a zenodo badge to this that always points to latest (zenodo will take care of this part). But should a docker container be deployed to docker hub?

@tkkuehn @Bradley-Karat @ataha24

**Comment by tkkuehn** [comment]
> @tkkuehn do you want to generate a token (as `BP_BAP_TOKEN`) for this action or shall I?

I think you should make it if you're writing the action anyway.

**Comment by kaitj** [comment]
> I think you should make it if you're writing the action anyway. 

Sounds good, I just generated one and added it to the repository secrets. Will expire in a year.

**Comment by kaitj** [comment]
Issue has been addressed and actions workflows have been created. Closing.
